spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

logging.level:
  org.hibernate.SQL: info

app:
  domain:
    url: https://www.cholog.com
    cors-origins: https://www.cholog.com, http://localhost:5173, http://localhost:5174
  is-local: false
  cookie-domain: www.cholog.com

cholog:
  logger:
    api-key: f98c78f3-8bea-4ead-a631-3d79bae44c11
  notification:
    poll:
      rate: 60000 # 알림 폴링 주기 (밀리초 단위, 예: 60000 = 1분)
      initialLookbackMinutes: 5 # 첫 폴링 시 또는 lastCheckedTimestamp가 없을 때 조회할 최근 시간 (분 단위)
      queryResultLimit: 100 # 한 번의 폴링 주기 및 알림 설정당 처리할 최대 로그 수

oauth:
  ssafy:
    redirect-uri: https://www.cholog.com/api/user/login/ssafy