spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/cholog
    username: cholog
    password: cholog207
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.ssafy.ddukdoc: DEBUG
    com.ssafy.ddukdoc.global.config.WebClientConfig: DEBUG
    com.zaxxer.hikari: TRACE

app:
  domain:
    url: http://localhost:5173
    cors-origins: http://localhost:5173, http://localhost:5174

cholog:
  notification:
    poll:
      rate: 60000 # 알림 폴링 주기 (밀리초 단위, 예: 60000 = 1분)
      initialLookbackMinutes: 5 # 첫 폴링 시 또는 lastCheckedTimestamp가 없을 때 조회할 최근 시간 (분 단위)
      queryResultLimit: 100 # 한 번의 폴링 주기 및 알림 설정당 처리할 최대 로그 수
