spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

logging.level:
  org.hibernate.SQL: info

app:
  domain:
    url: https://k12b207.p.ssafy.io
    cors-origins: https://k12b207.p.ssafy.io, http://localhost:5173, http://localhost:5174